---
- hosts: all
  user: root

#  vars:
#    users:
#      - username: galya
#        use_sudo: no

#      - username: kolya
#        use_sudo: yes

  tasks:
  - include_vars: users.yml
  - name: create sudo group
    group:
      name: orange_sudo
      state: present
    

  - name: add users | create users, shell, home dirs
    user: name={{ item.username }} shell=/bin/bash groups=orange_sudo createhome=yes comment='created with ansible'
    with_items: '{{users}}'

  - name: sudoers | update sudoers file and validate
    lineinfile:
      path: /etc/sudoers
      insertafter: EOF
      line: '%orange_sudo ALL=(ALL) NOPASSWD: ALL'
      regexp: '^%orange_sudo'
      state: present
      validate: /usr/sbin/visudo -cf %s
